//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by game.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_PNG1                        160
#define IDB_BACKGROUND                  163
#define IDB_LOGO                        163
#define IDB_SCREENBG1                   166
#define IDB_BITMAP3                     171
#define IDB_Blocks                      171
#define IDB_BITMAP4                     172
#define IDB_SCREEN_START                172
#define IDB_BITMAP5                     173
#define IDB_SCREEN_LOAD                 173
#define IDB_SCREEN_PREFERENCES          174
#define IDB_BITMAP7                     175
#define IDB_SCREEN_EXIT                 175
#define IDB_BITMAP6                     177
#define IDB_SCREEN_ABOUT                177
#define IDB_SCREEN_START_RED            178
#define IDB_BITMAP8                     179
#define IDB_SCREEN_LOAD_RED             179
#define IDB_SCREEN_PREFERENCES_RED      181
#define IDB_SCREEN_ABOUT_RED            182
#define IDB_BITMAP9                     183
#define IDB_SCREEN_EXIT_RED             183
#define IDR_TOOLBAR1                    184
#define IDB_BITMAP10                    185
#define IDB_BITMAP11                    188
#define IDB_Bg_1                        189
#define IDB_BREAK_0                     190
#define IDB_BITMAP13                    191
#define IDB_COIN_0                      191
#define IDB_BORDER_0                    192
#define IDB_BITMAP12                    193
#define IDB_Panel                       193
#define IDB_BITMAP14                    194
#define IDB_Test                        194
#define IDB_Test1                       195
#define IDB_BITMAP16                    196
#define IDB_PLAYER1_DW_1                197
#define IDB_BITMAP15                    198
#define IDB_PLAYER1_DW_2                198
#define IDB_PLAYER1_UP_1                199
#define IDB_PLAYER1_RE_1                200
#define IDB_PLAYER1_UP_2                201
#define IDB_BITMAP17                    202
#define IDB_PLAYER1_RE_2                202
#define IDB_PLAYER1_LE_2                203
#define IDB_PLAYER1_LE_1                204
#define IDB_SCREEN_QUIT_TO_MENU         205
#define IDB_SCREEN_RESUME               206
#define IDB_SCREEN_SAVE_GAME            207
#define IDB_SCREEN_QUIT_TO_MENU_RED     209
#define IDB_SCREEN_RESUME_RED           210
#define IDB_BITMAP18                    211
#define IDB_SCREEN_SAVE_GAME_RED        211
#define IDB_BOMB_1                      212
#define IDB_BOMB_2                      213
#define IDB_expC_1                      214
#define IDB_expC_2                      215
#define IDB_expC_3                      216
#define IDB_BITMAP19                    217
#define IDB_expC_4                      217
#define IDB_expH_1                      218
#define IDB_expH_2                      219
#define IDB_expH_3                      220
#define IDB_expH_4                      221
#define IDB_expV_1                      222
#define IDB_BITMAP21                    223
#define IDB_expV_2                      223
#define IDB_expV_3                      224
#define IDB_expV_4                      225
#define IDB_BREAK_1                     226
#define IDB_BREAK_2                     227
#define IDB_BITMAP22                    228
#define IDB_BREAK_3                     228
#define IDB_SCREEN_PREFENCES            229
#define IDB_SCREEN_FR                   230
#define IDB_SCREEN_CANCEL               231
#define IDB_SCREEN_CANCEL_RED           232
#define IDB_SCREEN_NO                   233
#define IDB_SCREEN_OK                   234
#define IDB_SCREEN_OK_RED               235
#define IDB_SCREEN_YES                  237
#define IDB_SCREEN_BACK                 238
#define IDB_BITMAP23                    239
#define IDB_SCREEN_BACK_RED             239
#define IDB_COIN_1                      240
#define IDB_COIN_2                      241
#define IDB_COIN_3                      242
#define IDB_COIN_4                      243
#define IDB_COIN_6                      244
#define IDB_COIN_5                      245
#define IDB_COIN_7                      246
#define IDB_COIN_8                      247
#define IDB_BITMAP20                    248
#define IDB_COIN_9                      248
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        249
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
